#! /usr/bin/zsh


gitbr () {
    git branch 2> /dev/null && git branch | print
}


local user='%F{cyan}<%n>%f'
local shortdir='%B%F{green}%2~%f%b'
local fulldir='%B%F{green}%~%f%b'
local rlo='%(?:%F{green}✔%f:%B%F{red}(%?✗%)%f%b)'
local usertype='%B%F{white}%#%f%b'
local timenow='%F{yellow}%*%f'
local iconroot=' '
local iconuser=' '
local usericon='%(#:%F{186}  %f:%F{042} %f)'
local gitbranch=''

# called just before each command is executed
# preexec() {
#       echo 'running preexec()'
#    Do all the pre-command jobs, like logging, etc
#}

# called just before displaying prompt
 precmd() {
#    echo 'running precmd()'
    gitbranch="%F{209}[$(gitbr)]%f"
#    echo use to set up prompt variables
}



PROMPT='${rlo} ${shortdir} ${usericon} '
RPROMPT='${timenow} ${fulldir} ${gitbranch} ${user}'

